tests/CI:
- tests/*

front-end:
- src/bb-themes/*

admin-panel:
- src/bb-themes/admin_*

composer:
- src/composer.json
- src/composer.lock

installer:
- src/install/*

payments:
- src/bb-library/Payment*

server-manager:
- src/bb-library/Server*

github-config:
- .github/*

hosting:
- src/bb-library/Server/Manager/*
